import Foundation
import Metal

public protocol InfiniteTileProducer: AnyObject { var valueChannels:Int {get}; var tileHeight:Int {get}; var tileWidth:Int {get}; var legalBatchSizes:[Int] {get}; func produceTiles(engine: InfiniteDiffusionEngine, keys:[WindowKey], commandBuffer: MTLCommandBuffer) throws -> [WindowKey:MetalTensor] }
public extension InfiniteTileProducer { var legalBatchSizes:[Int]{[1]} }

public final class InfiniteTensorStage {
    public let tensorID:String; public let window:WindowSpec; public let valueChannels:Int; public let producer:InfiniteTileProducer; public let scalarType:ScalarType
    public init(tensorID:String, window:WindowSpec, valueChannels:Int, producer:InfiniteTileProducer, scalarType:ScalarType = .float32) throws { guard window.channels == valueChannels + 1 else { throw TerrainDiffusionError.invalidShape("stage \(tensorID) must use packed C+1 window") }; self.tensorID=tensorID; self.window=window; self.valueChannels=valueChannels; self.producer=producer; self.scalarType=scalarType }
    public var packedShape: TensorShape { try! TensorShape(n:1,c:valueChannels+1,h:window.tileHeight,w:window.tileWidth) }
}

public struct QueryPlan: Sendable { public let tensorID:String; public let region:Region2D; public let windows:[WindowKey]; public let missingWindows:[WindowKey] }

public final class InfiniteDiffusionEngine {
    public let context:MetalContext; public let kernels:KernelEncoder; public let tileStore:TileStore
    private var stages:[String:InfiniteTensorStage]=[:]
    private var stack:[WindowKey]=[]
    private let lock=NSRecursiveLock()
    public init(context:MetalContext, tileStore:TileStore? = nil){self.context=context; self.kernels=KernelEncoder(context:context); self.tileStore=tileStore ?? LRUMetalTileStore()}
    public func register(_ stage:InfiniteTensorStage){stages[stage.tensorID]=stage}
    public func stage(_ id:String)throws->InfiniteTensorStage{ guard let s=stages[id] else { throw TerrainDiffusionError.missingTensor("No stage \(id)") }; return s }
    public func plan(tensorID:String, region:Region2D)throws->QueryPlan{ let s=try stage(tensorID); let ks=s.window.keys(overlapping:region,tensorID:tensorID); return QueryPlan(tensorID:tensorID, region:region, windows:ks, missingWindows:ks.filter{!tileStore.contains($0)}) }
    public func clear(tensorID:String?=nil){ tileStore.removeAll(prefix:tensorID) }
    @discardableResult public func prewarm(tensorID:String, region:Region2D)throws->QueryPlan{ let p=try plan(tensorID:tensorID, region:region); let cb=try context.makeCommandBuffer(label:"prewarm.\(tensorID)"); try ensureTiles(for:try stage(tensorID), keys:p.missingWindows, commandBuffer:cb); try context.runAndWait(cb); return p }
    public func queryNormalized(tensorID:String, region:Region2D, label:String?=nil)throws->MetalTensor{ let cb=try context.makeCommandBuffer(label:label ?? "query.\(tensorID)"); let t=try queryNormalized(tensorID:tensorID, region:region, commandBuffer:cb); try context.runAndWait(cb); return t }
    public func queryNormalized(tensorID:String, region:Region2D, commandBuffer:MTLCommandBuffer)throws->MetalTensor{ let s=try stage(tensorID); let packed=try queryPacked(tensorID:tensorID, region:region, commandBuffer:commandBuffer); let out=try context.allocate(shape:TensorShape(n:1,c:s.valueChannels,h:region.height,w:region.width), scalarType:s.scalarType, storageMode:.storageModePrivate, label:"norm.\(tensorID)"); try kernels.normalizePacked(commandBuffer:commandBuffer, inputPacked:packed, output:out); return out }
    public func queryPacked(tensorID:String, region:Region2D, commandBuffer:MTLCommandBuffer)throws->MetalTensor{ let s=try stage(tensorID); let out=try context.allocate(shape:TensorShape(n:1,c:s.valueChannels+1,h:region.height,w:region.width), scalarType:s.scalarType, storageMode:.storageModePrivate, label:"packed-query.\(tensorID)"); try kernels.fill(commandBuffer:commandBuffer, tensor:out, value:0); let ks=s.window.keys(overlapping:region,tensorID:tensorID); try ensureTiles(for:s, keys:ks, commandBuffer:commandBuffer); for k in ks { guard let tile=tileStore.get(k) else { throw TerrainDiffusionError.missingTensor("tile \(k)") }; if let (wl,ql)=s.window.localIntersection(windowKey:k, query:region){ try kernels.accumulateWindow(commandBuffer:commandBuffer, sourcePacked:tile, destinationPacked:out, sourceLocal:wl, destinationLocal:ql) } }; return out }
    private func chunkSize(_ legal:[Int], _ remaining:Int)->Int{ legal.filter{$0>0 && $0<=remaining}.max() ?? 1 }
    private func sortKeys(_ keys:inout [WindowKey]){ keys.sort{ a,b in if a.y != b.y { return a.y < b.y }; if a.x != b.x { return a.x < b.x }; return a.tensorID < b.tensorID } }
    private func ensureTiles(for stage:InfiniteTensorStage, keys requested:[WindowKey], commandBuffer:MTLCommandBuffer)throws{ lock.lock(); defer{lock.unlock()}; var keys=requested.filter{!tileStore.contains($0)}; guard !keys.isEmpty else{return}; sortKeys(&keys); var i=0; while i<keys.count { let cs=chunkSize(stage.producer.legalBatchSizes, keys.count-i); let chunk=Array(keys[i..<min(i+cs,keys.count)]); i += chunk.count; for k in chunk { if stack.contains(k){throw TerrainDiffusionError.invalidGraph("dependency cycle at \(k)")} }; stack.append(contentsOf:chunk); let values=try stage.producer.produceTiles(engine:self, keys:chunk, commandBuffer:commandBuffer); stack.removeLast(chunk.count); for k in chunk { guard let v=values[k] else { throw TerrainDiffusionError.missingTensor("producer did not return \(k)") }; let packed=try context.allocate(shape:stage.packedShape, scalarType:stage.scalarType, storageMode:.storageModePrivate, label:"packed.\(k)"); try kernels.packWeighted(commandBuffer:commandBuffer, input:v, outputPacked:packed); tileStore.put(packed, for:k, byteCost:packed.byteCount) } } }
}

public final class NoiseTileProducer: InfiniteTileProducer {
    public let valueChannels:Int; public let tileHeight:Int; public let tileWidth:Int; public let seed:UInt64; public let strideY:Int; public let strideX:Int; public let offsetY:Int; public let offsetX:Int; public let legalBatchSizes:[Int]
    public init(valueChannels:Int,tileHeight:Int,tileWidth:Int,seed:UInt64,strideY:Int?=nil,strideX:Int?=nil,offsetY:Int=0,offsetX:Int=0,legalBatchSizes:[Int]=[1,2,4,8,16]){self.valueChannels=valueChannels;self.tileHeight=tileHeight;self.tileWidth=tileWidth;self.seed=seed;self.strideY=strideY ?? tileHeight;self.strideX=strideX ?? tileWidth;self.offsetY=offsetY;self.offsetX=offsetX;self.legalBatchSizes=legalBatchSizes}
    public func produceTiles(engine:InfiniteDiffusionEngine, keys:[WindowKey], commandBuffer:MTLCommandBuffer)throws->[WindowKey:MetalTensor]{ var out:[WindowKey:MetalTensor]=[:]; for k in keys { let t=try engine.context.allocate(shape:TensorShape(n:1,c:valueChannels,h:tileHeight,w:tileWidth), scalarType:.float32, storageMode:.storageModePrivate, label:"noise.\(k)"); try engine.kernels.gaussian(commandBuffer:commandBuffer, out:t, seed:seed, originY:k.y*strideY+offsetY, originX:k.x*strideX+offsetX, tileH:tileHeight, tileW:tileWidth); out[k]=t }; return out }
}

public struct ConditioningDependency { public var name:String; public var tensorID:String; public var window:WindowSpec; public init(name:String,tensorID:String,window:WindowSpec){self.name=name;self.tensorID=tensorID;self.window=window} }

open class DenoisingTileProducer: InfiniteTileProducer {
    public let denoiser:MetalDenoiser; public let valueChannels:Int; public let tileHeight:Int; public let tileWidth:Int; public let inputTensorID:String?; public let inputWindow:WindowSpec?; public let noiseSeed:UInt64; public let phase:DiffusionPhaseParameters; public let conditioning:[ConditioningDependency]; public let legalBatchSizes:[Int]
    public init(denoiser:MetalDenoiser,inputTensorID:String?=nil,inputWindow:WindowSpec?=nil,noiseSeed:UInt64,phase:DiffusionPhaseParameters,conditioning:[ConditioningDependency]=[],legalBatchSizes:[Int]?=nil){self.denoiser=denoiser;self.valueChannels=denoiser.outputChannels;self.tileHeight=denoiser.tileHeight;self.tileWidth=denoiser.tileWidth;self.inputTensorID=inputTensorID;self.inputWindow=inputWindow;self.noiseSeed=noiseSeed;self.phase=phase;self.conditioning=conditioning;self.legalBatchSizes=legalBatchSizes ?? denoiser.legalBatchSizes}
    open func makeInput(engine:InfiniteDiffusionEngine,key:WindowKey,commandBuffer:MTLCommandBuffer)throws->MetalTensor{ if let id=inputTensorID, let iw=inputWindow { return try engine.queryNormalized(tensorID:id, region:iw.region(for:WindowKey(tensorID:id,y:key.y,x:key.x)), commandBuffer:commandBuffer) }; let t=try engine.context.allocate(shape:TensorShape(n:1,c:denoiser.inputChannels,h:tileHeight,w:tileWidth), scalarType:.float32, storageMode:.storageModePrivate, label:"denoise.noise.\(key)"); try engine.kernels.gaussian(commandBuffer:commandBuffer,out:t,seed:noiseSeed,originY:key.y*tileHeight,originX:key.x*tileWidth,tileH:tileHeight,tileW:tileWidth); return t }
    open func makeConditioning(engine:InfiniteDiffusionEngine,key:WindowKey,commandBuffer:MTLCommandBuffer)throws->[String:MetalTensor]{ var d:[String:MetalTensor]=[:]; for c in conditioning { d[c.name]=try engine.queryNormalized(tensorID:c.tensorID, region:c.window.region(for:WindowKey(tensorID:c.tensorID,y:key.y,x:key.x)), commandBuffer:commandBuffer) }; return d }
    open func postprocess(engine:InfiniteDiffusionEngine,key:WindowKey,input:MetalTensor,modelOutput:MetalTensor,commandBuffer:MTLCommandBuffer)throws->MetalTensor{ modelOutput }
    public func produceTiles(engine:InfiniteDiffusionEngine, keys:[WindowKey], commandBuffer:MTLCommandBuffer)throws->[WindowKey:MetalTensor]{ var out:[WindowKey:MetalTensor]=[:]; if keys.count == 1 { let k=keys[0]; let input=try makeInput(engine:engine,key:k,commandBuffer:commandBuffer); let cond=try makeConditioning(engine:engine,key:k,commandBuffer:commandBuffer); let r=try denoiser.encode(DenoiseBatch(commandBuffer:commandBuffer,input:input,conditioning:cond,windows:[DenoiseWindow(key:k,region:Region2D(y:k.y*tileHeight,x:k.x*tileWidth,height:tileHeight,width:tileWidth),phase:phase)],phase:phase), context:engine.context); out[k]=try postprocess(engine:engine,key:k,input:input,modelOutput:r,commandBuffer:commandBuffer); return out }
        let batch=try engine.context.allocate(shape:TensorShape(n:keys.count,c:denoiser.inputChannels,h:tileHeight,w:tileWidth), scalarType:.float32, storageMode:.storageModePrivate, label:"batch.\(denoiser.name)"); var inputs:[MetalTensor]=[]; var windows:[DenoiseWindow]=[]; for (i,k) in keys.enumerated(){ let inp=try makeInput(engine:engine,key:k,commandBuffer:commandBuffer); inputs.append(inp); try engine.kernels.copyTileToBatch(commandBuffer:commandBuffer, source:inp, destinationBatch:batch, batchIndex:i); windows.append(DenoiseWindow(key:k,region:Region2D(y:k.y*tileHeight,x:k.x*tileWidth,height:tileHeight,width:tileWidth),phase:phase)) }
        let bout=try denoiser.encode(DenoiseBatch(commandBuffer:commandBuffer,input:batch,conditioning:[:],windows:windows,phase:phase), context:engine.context)
        for (i,k) in keys.enumerated(){ let t=try engine.context.allocate(shape:TensorShape(n:1,c:denoiser.outputChannels,h:tileHeight,w:tileWidth), scalarType:.float32, storageMode:.storageModePrivate, label:"tile.\(k)"); try engine.kernels.extractBatchTile(commandBuffer:commandBuffer, sourceBatch:bout, destination:t, batchIndex:i); out[k]=try postprocess(engine:engine,key:k,input:inputs[i],modelOutput:t,commandBuffer:commandBuffer) }
        return out }
}

public final class ConsistencyUpdateProducer: DenoisingTileProducer {
    public let updateTime:Float; public let sigmaData:Float; public let negateOutput:Bool
    public init(denoiser:MetalDenoiser,inputTensorID:String?,inputWindow:WindowSpec?,noiseSeed:UInt64,phase:DiffusionPhaseParameters,conditioning:[ConditioningDependency]=[],updateTime:Float,sigmaData:Float=0.5,negateOutput:Bool=true,legalBatchSizes:[Int]?=nil){self.updateTime=updateTime;self.sigmaData=sigmaData;self.negateOutput=negateOutput; super.init(denoiser:denoiser,inputTensorID:inputTensorID,inputWindow:inputWindow,noiseSeed:noiseSeed,phase:phase,conditioning:conditioning,legalBatchSizes:legalBatchSizes)}
    public override func makeInput(engine:InfiniteDiffusionEngine,key:WindowKey,commandBuffer:MTLCommandBuffer)throws->MetalTensor{ let base:MetalTensor; if let id=inputTensorID, let iw=inputWindow { let n=try engine.queryNormalized(tensorID:id, region:iw.region(for:WindowKey(tensorID:id,y:key.y,x:key.x)), commandBuffer:commandBuffer); base=try engine.context.allocate(shape:n.shape, scalarType:.float32, storageMode:.storageModePrivate, label:"base.sd"); try engine.kernels.unaryScale(commandBuffer:commandBuffer, source:n, destination:base, scale:sigmaData) } else { base=try engine.context.allocate(shape:TensorShape(n:1,c:denoiser.inputChannels,h:tileHeight,w:tileWidth), scalarType:.float32, storageMode:.storageModePrivate, label:"zero"); try engine.kernels.fill(commandBuffer:commandBuffer,tensor:base,value:0) }; let noise=try engine.context.allocate(shape:base.shape, scalarType:.float32, storageMode:.storageModePrivate, label:"z"); try engine.kernels.gaussian(commandBuffer:commandBuffer,out:noise,seed:noiseSeed,originY:key.y*tileHeight,originX:key.x*tileWidth,tileH:tileHeight,tileW:tileWidth,sigma:sigmaData); let xt=try engine.context.allocate(shape:base.shape, scalarType:.float32, storageMode:.storageModePrivate, label:"xt"); try engine.kernels.linearMix(commandBuffer:commandBuffer,a:base,b:noise,destination:xt,weightA:Float(cos(Double(updateTime))),weightB:Float(sin(Double(updateTime)))); let min=try engine.context.allocate(shape:base.shape, scalarType:.float32, storageMode:.storageModePrivate, label:"modelin"); try engine.kernels.unaryScale(commandBuffer:commandBuffer, source:xt, destination:min, scale:1/sigmaData); return min }
    public override func postprocess(engine:InfiniteDiffusionEngine,key:WindowKey,input:MetalTensor,modelOutput:MetalTensor,commandBuffer:MTLCommandBuffer)throws->MetalTensor{ let pred:MetalTensor; if negateOutput { pred=try engine.context.allocate(shape:modelOutput.shape, scalarType:.float32, storageMode:.storageModePrivate, label:"pred"); try engine.kernels.unaryScale(commandBuffer:commandBuffer, source:modelOutput, destination:pred, scale:-1) } else { pred=modelOutput }; let out=try engine.context.allocate(shape:modelOutput.shape, scalarType:.float32, storageMode:.storageModePrivate, label:"consistency.out"); try engine.kernels.linearMix(commandBuffer:commandBuffer,a:input,b:pred,destination:out,weightA:Float(cos(Double(updateTime))),weightB:-Float(sin(Double(updateTime)))); return out }
}
