import Foundation
import Metal

public final class TerrainTransforms {
    public let context: MetalContext
    public let kernels: KernelEncoder
    public init(context: MetalContext){ self.context=context; self.kernels=KernelEncoder(context:context) }
    public func signedSqrt(_ x: MetalTensor, commandBuffer: MTLCommandBuffer) throws -> MetalTensor { let y=try context.allocate(shape:x.shape, scalarType:.float32, storageMode:.storageModePrivate, label:"signed_sqrt"); try kernels.signedSqrt(commandBuffer:commandBuffer, source:x, destination:y); return y }
    public func inverseSignedSqrt(_ x: MetalTensor, commandBuffer: MTLCommandBuffer) throws -> MetalTensor { let y=try context.allocate(shape:x.shape, scalarType:.float32, storageMode:.storageModePrivate, label:"inverse_signed_sqrt"); try kernels.inverseSignedSqrt(commandBuffer:commandBuffer, source:x, destination:y); return y }
    public func boxDownsample(_ x: MetalTensor, factor: Int, commandBuffer: MTLCommandBuffer) throws -> MetalTensor { let out=try context.allocate(shape:TensorShape(n:1,c:x.shape.c,h:max(1,x.shape.h/factor),w:max(1,x.shape.w/factor)), scalarType:.float32, storageMode:.storageModePrivate, label:"downsample"); let pso=try context.pipeline("td_box_downsample"); let enc=commandBuffer.makeComputeCommandEncoder()!; enc.setComputePipelineState(pso); enc.setBuffer(x.buffer,offset:x.byteOffset,index:0); enc.setBuffer(out.buffer,offset:out.byteOffset,index:1); var d=Int8Uniforms(x.shape.c,x.shape.h,x.shape.w,out.shape.h,out.shape.w,factor,factor,0); enc.setBytes(&d,length:MemoryLayout<Int8Uniforms>.stride,index:2); enc.dispatch3D(pipeline:pso,width:out.shape.w,height:out.shape.h,depth:out.shape.c); enc.endEncoding(); return out }
    public func nearestUpsample(_ x: MetalTensor, height: Int, width: Int, commandBuffer: MTLCommandBuffer) throws -> MetalTensor { let fy=max(1,height/x.shape.h), fx=max(1,width/x.shape.w); let out=try context.allocate(shape:TensorShape(n:1,c:x.shape.c,h:height,w:width), scalarType:.float32, storageMode:.storageModePrivate, label:"upsample"); let pso=try context.pipeline("td_nearest_upsample"); let enc=commandBuffer.makeComputeCommandEncoder()!; enc.setComputePipelineState(pso); enc.setBuffer(x.buffer,offset:x.byteOffset,index:0); enc.setBuffer(out.buffer,offset:out.byteOffset,index:1); var d=Int8Uniforms(x.shape.c,x.shape.h,x.shape.w,out.shape.h,out.shape.w,fy,fx,0); enc.setBytes(&d,length:MemoryLayout<Int8Uniforms>.stride,index:2); enc.dispatch3D(pipeline:pso,width:out.shape.w,height:out.shape.h,depth:out.shape.c); enc.endEncoding(); return out }
}
